### ISSUE TITLE
Remove quotation marks from Wikilink

### ISSUE THREAD

**Issue by kazdonkai** [Trikzon/obsidian-frontmatter-links#9]
Currently, Wikilink is in citation format, but the bracket name allows us to determine that it is Wikilink, so could you please make it so that it is linked even if it is not in citation format?
"[[Wikilink]]" → [[Wikilink]]

**Comment by Trikzon** [comment]
YAML doesn't parse wiki links as a wiki link. It attempts to parse it as an array and fails. This causes the following to not work when using, for example, dataview to process the metadata.

```
---
link: [[Wikilink]]
---
```

Because it isn't correct YAML, it would be wrong for this plugin to treat it as if it was.

Instead, you should follow the correct YAML style and do the following:
```
---
link: "[[Wikilink]]"
---
```
